# Generated by Django 4.2.11 on 2024-03-27 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=100)),
                ('color', models.CharField(default='black', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Rectangle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(default=5)),
                ('width', models.FloatField(default=5)),
                ('color', models.CharField(default='red', max_length=30)),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obrazkiapp.picture')),
            ],
        ),
    ]
