# Generated by Django 4.2.11 on 2024-03-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrazkiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='name',
            field=models.CharField(default='New Picturepython manage.py makemigrations', max_length=200),
        ),
    ]
