# Generated by Django 4.2.11 on 2024-03-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrazkiapp', '0002_picture_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='size',
            new_name='height',
        ),
        migrations.AddField(
            model_name='picture',
            name='width',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='picture',
            name='name',
            field=models.CharField(default='New Picture', max_length=200),
        ),
    ]
