# Generated by Django 4.2.11 on 2024-03-27 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obrazkiapp', '0004_rectangle_x_rectangle_y_alter_picture_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='color',
        ),
    ]
